version: "3.7"
services:
  api_service:
    build: .
    restart: always
    ports:
      - 8080:8080
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql_db:3306/gaticketdb
      SPRING_DATASOURCE_USERNAME: myuser
      SPRING_DATASOURCE_PASSWORD: mypass
    depends_on:
      - mysql_db
    networks:
      - mynetwork
    command: sh -c './wait-for mysql_db:3306 -- mvn spring-boot:run'
  mysql_db:
    image: "mysql:8.0"
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: gaticketdb
      MYSQL_USER: myuser
      MYSQL_PASSWORD: mypass
    networks:
      - mynetwork

  apache_php:
    image: php:apache
    ports:
      - "80:80"
    volumes:
      - /Applications/MAMP/htdocs/GaticketWeb:/var/www/html/GaticketWeb
    networks:
      - mynetwork

networks:
  mynetwork:
