openapi: 3.0.1
info:
  title: GATICKET-API
  description: API description in Markdown.
  version: 1.0.0
servers:
  - url: ''
tags:
  - name: users
  - name: devices
  - name: types
  - name: net
  - name: units
  - name: incidences
paths:
  /devices/findByUSerialNumber:
    get:
      tags:
        - devices
      summary: Get device by Serial Number
      description: Ahow device with serial number
      operationId: findDevicesBySerialNumber
      parameters:
        - name: serial_number
          in: query
          description: Unique Idetification serial number
          required: true
          schema:
            type: string
      responses:
        '200':
          description: successful operation
          content:
            application/json:
